* ษออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : TEL.PRG              บ
* บ COMENTARIO    : GESTION DE TELAS     บ
* บ                 GENERICA             บ
* ฬออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER             บ
* บ FECHA      : 30/08/95 15:13          บ
* บ COPYRIGHT  : 1995 by GREGORIO REINER บ
* ศออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:43pm
PROCEDURE TEL
EXTERNAL PROCEDURE ELITEL
=OPTEL()
ULPR=PROGRAM()
RETURN MIX("Tela","Telas","TELA","TELAS","TELTEX","TELCOD","ORDTEL","F")
