* ษอออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : SEC.PRG               บ
* บ COMENTARIO    : GESTION DE Secciขnes  บ
* ฬอออออออออออออออออออออออออออออออออออออออน
* บ FECHA      : 26/10/95 15:59           บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER  บ
* ศอออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:23pm
PROCEDURE SEC
EXTERNAL PROCEDURE ELISEC
=OPSEC()
ULPR=PROGRAM()
RETURN MIX("Secciขn","Secciones","SECCION","SECCIONES","SECTEX","SECCOD","ORDSEC","S")
