* ษออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : ETA.PRG              บ
* บ COMENTARIO    : ETAPAS MEDICAS       บ
* ฬออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER             บ
* บ FECHA      : 09-05-93 - 01:09:22pm   บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER บ
* ศออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 00:34am
PROCEDURE ETA
EXTERNAL PROCEDURE ELIETA
=OPETA()
ULPR=PROGRAM()
RETURN MIX("Etapa","Etapas","ETAPA","ETAPAS","ETATEX","ETACOD","ORDETA",'E')
