PROCEDURE SHIT
RETURN .T.
procedure ELIUSU 
return
procedure ELIZON 
return
procedure ELICOMS 
return
procedure ELIBAN 
return
procedure ELICLI 
return
procedure ELIIVA 
return
procedure ELIPAG 
return
procedure ELIAGE 
return
procedure ELIETA 
return
procedure ELIEST 
return
procedure ELIGAS 
return
procedure ELIGRU 
return
procedure ELIOPK 
return
procedure ELITAL 
return
procedure ELITAR 
return
procedure ELITIP 
return
procedure ELIDNI 
return
procedure ELITFA 
return
procedure ELITPR 
return
FUNCTION OPCCL 
RETURN .T.
FUNCTION LCCL 
RETURN .T.
FUNCTION NOOPCLI 
RETURN .T.
FUNCTION ESDEBE 
RETURN .T.
FUNCTION OPCCLH 
RETURN .T.
FUNCTION IMPUTMAN 
RETURN .T.
FUNCTION SCCLPAR 
RETURN .T.
FUNCTION OPHOR 
RETURN .T.
