* ษออออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : FUERARED.PRG               บ
* บ COMENTARIO    : AVISA QUE SALGAN DE LA RED บ
* ฬออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                   บ
* บ FECHA      : 03-12-94                      บ
* บ HORA       : 09:46:01am                    บ
* บ COPYRIGHT  : 1994 by GREGORIO REINER       บ
* ศออออออออออออออออออออออออออออออออออออออออออออผ
FUNCTION FUERARED
RETURN CARTEL("LA OPERACION SOLICITADA ES IMPOSIBLE HABIENDO",;
"USUARIOS EN LA RED. ASEGURESE DE QUE LA SUYA ES LA",;
" ******* UNICA ESTACION TRABAJANDO ******* ",;
"PULSE UNA TECLA PARA CONTINUAR Y [ESC] PARA ANULAR")

