* ษออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออป
* บ FUNCION    : REOPVIA.PRG                                                 บ
* บ COMENTARIO : CIERRA Y ABRE BASE DE VIAJANTES Y ZONAS                     บ
* ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                                                 บ
* บ FECHA      : 07-25-93                                                    บ
* บ HORA       : 02:10:15pm                                                  บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER                                     บ
* ศออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
FUNCTION REOPVIA
USE IN VIA
IF USED("VIX")
	USE IN VIX
ENDIF
RETURN OPVIA()
