* ษอออออออออออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : ACT.PRG                           บ
* บ COMENTARIO    : GESTION DE TIPOS DE ACTUALIZACION บ
* ฬอออออออออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                          บ
* บ FECHA      : 09-05-93 - 01:09:40pm                บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER              บ
* ศอออออออออออออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 00:40am
PROCEDURE ACT
EXTERNAL PROCEDURE ELIACT
=OPACT()
ULPR=PROGRAM()
RETURN MIX("Tipo de Actualizaciขn","Tipos de Actualizaciขn","TIPO DE ACTUALIZACION","TIPOS DE ACTUALIZACION","ACTTEX","ACTCOD","ORDACT",'A')
