********************************************************************************
*-- Programa: RNDX1.PRG
*-- Fecha   : 06/05/91 02:48pm
*-- Version : G. REINER
*-- Notas   : GENERA EL POPUP DE RECONSTRUCCION DE LOS ARCHIVOS
********************************************************************************
PARAMETER R,C
respuesta='rndx#'+str(R)+'#'+str(C)+'#Tipo de Restauraci¢n#3#\<Reindexa#Reconstruye \<Indice'
RETURN defpop()
