* ษอออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : APL.PRG                 บ
* บ COMENTARIO    : GESTION DE APLICACIONES บ
* ฬอออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                บ
* บ FECHA      : 09-05-93 - 01:09:40pm      บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER    บ
* ศอออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 00:49am
PROCEDURE APL
EXTERNAL PROCEDURE ELIAPL
=OPAPL()
ULPR=PROGRAM()
RETURN MIX("Aplicaciขn","Aplicaciones","APLICACION","APLICACIONES","APLTEX","APLCOD","ORDAPL",'A')
