*
*                   CARGA LAS VARIABLES DEL DISCO
*
* CARGA.PRG
*
restore from XVARIABL additive
store Q1 to KMESES[1]
store Q2 to KMESES[2]
store Q3 to KMESES[3]
store Q4 to KMESES[4]
store Q5 to KMESES[5]
store Q6 to KMESES[6]
store Q7 to KMESES[7]
store Q8 to KMESES[8]
store Q9 to KMESES[9]
store Q10 to KMESES[10]
store Q11 to KMESES[11]
store Q12 to KMESES[12]
store Q13 to KASIENTO[1]
store Q14 to KASIENTO[2]
store Q15 to KASIENTO[3]
store Q16 to KASIENTO[4]
store Q17 to KASIENTO[5]
store Q18 to KASIENTO[6]
store Q19 to KASIENTO[7]
store Q20 to KASIENTO[8]
store Q21 to KASIENTO[9]
store Q22 to KASIENTO[10]
store Q23 to KASIENTO[11]
store Q24 to KASIENTO[12]
store Q25 to KMOVIMIENTO[1]
store Q26 to KMOVIMIENTO[2]
store Q27 to KMOVIMIENTO[3]
store Q28 to KMOVIMIENTO[4]
store Q29 to KMOVIMIENTO[5]
store Q30 to KMOVIMIENTO[6]
store Q31 to KMOVIMIENTO[7]
store Q32 to KMOVIMIENTO[8]
store Q33 to KMOVIMIENTO[9]
store Q34 to KMOVIMIENTO[10]
store Q35 to KMOVIMIENTO[11]
store Q36 to KMOVIMIENTO[12]
store Q37 to KPERINIC
store Q38 to KPERIODO
store Q39 to KREPORTE
store Q42 to XCRFV
store Q43 to XDBFV
store Q44 to XCRFC
store Q45 to XDBFC
store Q46 to TIVA1
store Q47 to TIVA2
store Q48 to PROPIOIVA
store iif(type("q1000")#"C","1",q1000) to KPRES
=MEN_LIN(SYSNOMBRE)
return
