* ษอออออออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : MDD.PRG                       บ
* บ COMENTARIO    : GESTION DE UNIDADES DE MEDIDA บ
* ฬอออออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                      บ
* บ FECHA      : 10-26-93 - 12:51:06pm            บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER          บ
* ศอออออออออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:56pm
PROCEDURE MDD
EXTERNAL PROCEDURE ELIMDD
=OPMDD()
ULPR=PROGRAM()
RETURN MIX("Unidad de Medida","Unidades de Medida","UN. MEDIDA","UN. MEDIDA","MDDTEX","MDDCOD","ORDMDD","5")
