* ษออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : GRU.PRG              บ
* บ COMENTARIO    : GESTION DE GRUPOS    บ
* ฬออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER             บ
* บ FECHA      : 09-05-93                บ
* บ HORA       : 01:09:40pm              บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER บ
* ศออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 31/08/95 15:45
PROCEDURE GRU
EXTERNAL PROCEDURE ELIGRU
=OPGRU()
ULPR=PROGRAM()
RETURN MIX("Grupo","Grupos","GRUPO","GRUPOS","GRUTEX","GRUCOD","ORDGRU",'U')
