* ษออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : ESP.PRG                บ
* บ COMENTARIO    : ESPECIALIDADES MEDICAS บ
* ฬออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER               บ
* บ FECHA      : 09-05-93 - 01:09:22pm     บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER   บ
* ศออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 00:32am
PROCEDURE ESP
EXTERNAL PROCEDURE ELIESP
=OPESP()
ULPR=PROGRAM()
RETURN MIX("Especialidad","Especialidades","ESPECIALIDAD","ESPECIALIDADES","ESPTEX","ESPCOD","ORDESP",'E')
