********************************************************************************
*-- Programa: GRL2.PRG
*-- Fecha   : 07-28-92 04:30pm
*-- Version : G. REINER *-- Notas   : DEFINE EL POPUP NADA
********************************************************************************
PARAMETER R,C,t
respuesta='nada#'+STR(R)+'#'+STR(C)+'#'+t+'#3#\<Completo#\<Especie#\<Variedad#Ca\<lidad'
=DEFPOP()
RETURN
*: EOF: GRL2.PRG
