* ษออออออออออออออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : SUE.PRG                              บ
* บ COMENTARIO    : GESTION DE SUELAS (ZUELA -> COLORES) บ
* ฬออออออออออออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                             บ
* บ FECHA      : 09-05-93 - 01:09:40pm                   บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER                 บ
* ศออออออออออออออออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:47pm
EXTERNAL PROCEDURE ELISUE
=OPSUE()
ULPR=PROGRAM()
RETURN MIX(PROP(ZUELA),PROP(ZUELAS),UPPE(ZUELA),UPPE(ZUELAS),"SUETEX","SUECOD","ORDSUE","S")
