******************************************************************************
*-- Programa: mer.prg
*-- Fecha   : 06/05/91 03:21pm
*-- Version : G. REINER
*-- Notas   : DERIVA A OPERACIONES DE repeticion de mercaderias
********************************************************************************
DO CASE
CASE BAR()=1
   DO rmer1
CASE BAR()=2
   do rmer2
ENDCASE
ulpr=PROGRAM()
=MEN_LIN(BOTOM)
return
* EOF - INDENT
