DO CASE
CASE BAR()=2
   =SAVGENE()
   RELE abio,abios,tella,tellas,austral,australes,zuela,zuelas,ruvro,ruvros,llinea,llineas,janname,coefseg,usador,xacancho,xachoja,unid,JANNRO
   RELE sstm,ulpr,espere,grabando,tratando,IMPRIMIENDO,LARGOIM,LINEA,LARGO,TEN,nlq,offnlq,UNDER,OFFUNDER
   RELE pds,favri,ulpr,sstm,WIDE,OFFWIDE
   A=PATHCPR   
   RELE ALL LIKE mader*
   RELE ALL LIKE xa*
   RELE ALL LIKE PAT*
   =SAVPOCPR(A)
   QUIT
ENDCASE
RETURN
