********************************************************************************
*-- Programa: OPPOLX.PRG
*-- Fecha   : 11-09-92 04:10pm
*-- Version : G. REINER
*-- Notas   : ABRE ARCHIVO DE POLIGONAL EXCLUSIVE
********************************************************************************
=men_lin('Abriendo archivo de Poligonal')
SELE 3
USE (PATHPRO+'\POLIGONA') ORDER ALIAS POL EXCL
=men_lin(botom)
RETURN
