****************************************************************************
*-- Programa: mer.prg
*-- Fecha   : 06/05/91 03:21pm
*-- Version : G. REINER
*-- Notas   : DERIVA A OPERACIONES DE PROCESOS DE FABRICACION
********************************************************************************
ulpr=PROGRAM()
=cabpan1()
do oppol
=OPPRO()
DO CASE
CASE BAR()=1
	do ipol
ENDCASE
ulpr=PROGRAM()
=MEN_LIN(BOTOM)
UNLO ALL
RETURN
