* ษออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : MAR.PRG              บ
* บ COMENTARIO    : GESTION DE MARCAS    บ
* ฬออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER             บ
* บ FECHA      : 09-05-93 - 01:09:40pm   บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER บ
* ศออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 01:00am
PROCEDURE MAR
EXTERNAL PROCEDURE ELIMAR
=OPMAR()
ULPR=PROGRAM()
RETURN MIX("Marca","Marcas","MARCA","MARCAS","MARTEX","MARCOD","ORDMAR",'M')
