********************************************************************************
*-- Programa: OPKAR.PRG
*-- Fecha   : 06/18/91
*-- Version : G. REINER
*-- Notas   : ABRE ARCHIVO KARDEX DE MERCADERIAS TERMINADAS
********************************************************************************
=men_lin('Abriendo archivo de Kardex')
SELE 17
   USE (PATHVEN+'\KARDEX') ALIAS kar excl
=MEN_LIN(BOTOM)
RETURN
*: EOF: OPKAR.PRG
