* зд Function дддддддддддддддддддддддддддддддддддддд©
* Ё  Application: REABRE BASE DE FACTURA DE COMPRAS Ё
* Ё    File Name: REOPFAR.PRG                       Ё
* Ё       Author: G. REINER                         Ё
* Ё Date created: 09-04-92                          Ё
* Ё Time created: 01:32:42am                        Ё
* юддддддддддддддддддддддддддддддддддддддддддддддддды
FUNCTION REOPFAR
USE IN FArx
USE IN FAR
return OPFAR()

