  **** OJO SQL ****
  SELECT ALL ARTICULO,MERCA FROM MER INTO CURSOR NADAS ORDER BY MERCA
 DEFI POPU NADAS FROM 0,0 PROM FIEL MERCA;
  FOOTER " Art¡culo"+alltrim(msg)+" " ;
  TITL ' Mercader¡as ' ;  
  ON SELE POPU NADAS DO RESP1
  ventant=wontop()
  acti scre
  store nul to respuesta
  ACTI POPUP NADAS
  STOR !EMPTY(respuesta) TO respuesta
  SELE MER
  =IIF(RESPUESTA,SEEK(NADAS.ARTICULO),.T.)
  USE IN NADAS
