* ÚÄ FUNCION  ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
* ³  Description: LP_P2.PRG                                                  ³
* ³       Author: G. REINER                                                  ³
* ³ Date created: 11-06-92                                                   ³
* ³ Time created: 02:11:32am                                                 ³
* ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
FUNCTION LP_P2
	_WRAP=.F.
	?
	? "RUBRO   :"
	?? RUB1
	? "SUBRUBRO:"
	?? SRUB1
	_WRAP=.T.
RETURN .T.
