* ษออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : ZON.PRG              บ
* บ COMENTARIO    : GESTION DE ZONAS     บ
* ฬออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER             บ
* บ FECHA      : 09-05-93 - 01:09:40pm   บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER บ
* ศออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:33pm
PROCEDURE ZON
EXTERNAL PROCEDURE ELIZON
=OPZON()
ULPR=PROGRAM()
RETURN MIX("Zona","Zonas","ZONA","ZONAS","ZONTEX","ZONCOD","ORDZON","Z")
