* ษอออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : PRV.PRG                 บ
* บ COMENTARIO    : GESTION DE PROVINCIAS   บ
* ฬอออออออออออออออออออออออออออออออออออออออออน
* บ FECHA      : 09-05-93 - 01:09:40pm      บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER    บ
* ศอออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:23pm
PROCEDURE PRV
EXTERNAL PROCEDURE ELIPRV
=OPPRV()
ULPR=PROGRAM()
RETURN MIX("Provincia","Provincias","PROVINCIA","PROVINCIAS","PRVTEX","PRVCOD","ORDPRV","P")
