* ษอออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : TST.PRG                 บ
* บ COMENTARIO    : GESTION DE ESTRUCTURA   บ
* ฬอออออออออออออออออออออออออออออออออออออออออน
* บ FECHA      : 09-05-93 - 01:09:40pm      บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER    บ
* ศอออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-30-95 11:23pm
PROCEDURE TST
EXTERNAL PROCEDURE ELITST
=OPTST()
ULPR=PROGRAM()
RETURN MIX("Estructura","Estructuras","ESTRUCTURA","ESTRUCTURAS","TSTTEX","TSTCOD","ORDTST","N")
