* ษออออออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : TPR.PRG                      บ
* บ COMENTARIO    : GESTION DE TIPOS DE PRACTICA บ
* ฬออออออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                     บ
* บ FECHA      : 09-05-93 - 01:09:40pm           บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER         บ
* ศออออออออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 01:06am
PROCEDURE TPR
EXTERNAL PROCEDURE ELITPR
=OPTPR()
ULPR=PROGRAM()
RETURN MIX("Tipo de Pr ctica","Tipos de Pr ctica","TIPO DE PRACTICA","TIPOS DE PRACTICA","TPRTEX","TPRCOD","ORDTPR",'I')
