build exe c:\temp\presu    from presu
build exe c:\temp\consdev  from consdev
build exe c:\temp\consigna from consigna 
build exe c:\temp\fas      from facturas 
build exe c:\temp\trazcpra from trazcpra 
build exe c:\temp\trazdev  from trazdev  

build exe c:\temp\xpresu   from xpresu
build exe c:\temp\xconsdev from xconsdev
build exe c:\temp\xconsign from xconsign
build exe c:\temp\xfactura from xfactura  
build exe c:\temp\xtrazcpr from xtrazcpr 
build exe c:\temp\xtrazdev from xtrazdev  


