********************************************************************************
*-- Programa: ELILET.PRG
*-- Fecha   : 4/10/89
*-- Version : G. REINER
*-- Notas   : ELIGE EL TIPO DE LETRA
********************************************************************************
 
 
ACTI POPU ANCHO
ANCLET=RESPUESTA
ACTI POPU ALTO
ALTOLET=RESPUESTA
ACTI POPU REVE
REVELET=RESPUESTA
ACTI POPU ITAL
ITALET=RESPUESTA
ACTI POPU CALI
CALILET=RESPUESTA
RETURN
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
