********************************************************************************
*-- Programa: ESPERE.PRG
*-- Fecha   : 20/10/89
*-- Version : G. REINER
*-- Notas   : GENERA ESPERA
********************************************************************************
DEFI WIND WIN FROM 10,0 TO 14,79 DOUB
ACTI WIND WIN
CLEAR
DO TIT2 WITH 1,' ESPERE POR FAVOR - GENERANDO MENUES ','I*/W',78
RETURN
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
