USE F:\SISTEMAS\VENTAS\VENTASA\VENDEDOR IN 1 ALIAS VEND
USE F:\SISTEMAS\VENTAS\VENTASA\FACTURA  IN 2 ALIAS FAC
USE F:\SISTEMAS\VENTAS\VENTASA\FACTUDAT IN 3 ALIAS FAX
SELECT SUM(FAX.CANTIDAD), FAC.USUARIO, VEND.CODIGO, VEND.NOMBRE ;
	FROM FAX, FAC, VEND ;
	WHERE 	BETW(FAC.FECHAEM, DATE()-100, DATE()) AND ;
			ARTICULO = ELARTI AND ;
			FAC.FACTURA = FAX.FACTURA AND ;
			FAC.USUARIO = VEND.NOMBRE 
	GROUP BY CODIGO

