use f:\sistemas\ventas\ventasa\personas alias nue in 1
use h:\temp\personas alias vie in 2
sele 2
set orde to agecod
sele 1
set orde to agecod
set rela to codcli into vie
replace localidad with vie.localidad all

sele 2
set orde to procod
sele 1
set orde to procod
set rela to codcli into vie
replace localidad with vie.localidad all

sele 2
set orde to intcod
sele 1
set orde to intcod
set rela to codcli into vie
replace localidad with vie.localidad all
