use \\bochi\zip\ventasa\cccli 		in 0 alias xccl
use \\bochi\zip\ventasa\factura		in 0 alias xfac
use \\bochi\zip\ventasa\factudat	in 0 alias xfad
use \\bochi\zip\ventasa\lote		in 0 alias xlot
use \\bochi\zip\ventasa\ccstock		in 0 alias xccs

use \\willy\archivos\sistemas\ventas\ventasa\cccli		in 0 alias ccl
use \\willy\archivos\sistemas\ventas\ventasa\factura	in 0 alias fac
use \\willy\archivos\sistemas\ventas\ventasa\factudat	in 0 alias fad
use \\willy\archivos\sistemas\ventas\ventasa\lote		in 0 alias lot
use \\willy\archivos\sistemas\ventas\ventasa\ccstock	in 0 alias ccs




