*:*********************************************************************
*:
*:        Program: RESP1.PRG
*:
*:         System:
*:         Author:
*:      Copyright (c) 1991,
*:  Last modified: 04/24/160     12:17
*:
*:      Called by: LISCATE.PRG
*:
*:      Documented 02/21/91 at 11:04               FoxDoc  version 2.01
*:*********************************************************************
********************************************************************************
*-- Programa: RESP1.PRG
*-- Fecha   : 26/08/89
*-- Version : G. REINER
*-- Notas   : LLEGA DE TODOS LOS POPUS
*      LA RESPUESTA SE GUARDA EN 'RESPUESTA' (VARIABLE PUBLICA)
********************************************************************************
STOR BAR() TO respuesta
DEAC POPU
RETURN
*: EOF: RESP1.PRG
 
