* ษอออออออออออออออออออออออออออออออออออออออออออป
* บ PROCEDIMIENTO : THO.PRG                   บ
* บ COMENTARIO    : GESTION DE TIPOS DE HORA  บ
* ฬอออออออออออออออออออออออออออออออออออออออออออน
* บ AUTOR      : GOYO REINER                  บ
* บ FECHA      : 26/10/95 13:29               บ
* บ COPYRIGHT  : 1993 by GREGORIO REINER      บ
* ศอออออออออออออออออออออออออออออออออออออออออออผ
* REDUCCION 08-31-95 01:06am
PROCEDURE THO
EXTERNAL PROCEDURE ELITHO
=OPTHO()
ULPR=PROGRAM()
RETURN MIX("Tipo de Hora","Tipos de Hora","TIPO DE HORA","TIPOS DE HORA","THOTEX","THOCOD","ORDTHO",'H')
